name: End to end tests with OBS

env:
  NODE_OPTIONS: --max-http-header-size=4096

on:
  workflow_dispatch:
    inputs:
      obs-enabled:
        description: "Enable OBS WebSocket?"
        required: true
        default: false
        type: boolean

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  id-token: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  install:
    name: 📦 Install Packages
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "22.15"
          cache: "pnpm"

  setup-obs:
    name: Setup OBS WebSocket
    needs: [install]
    if: ${{ github.event.inputs.obs-enabled == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      obs-password: ${{ steps.obs-password.outputs.password }}
    steps:
      - name: Generate random password for obs (not config)
        id: obs-password
        run: echo "password=$(openssl rand -hex 12)" >> $GITHUB_OUTPUT

      - name: Install OBS Studio and WS
        run: |
          sudo apt-get update
          sudo apt-get install -y obs-studio obs-websocket

      - name: Configure OBS WebSocket
        run: |
          mkdir -p ~/.config/obs-studio/plugin_config/obs-websocket
          echo '{
            "enabled": true,
            "serverPort": 4455,
            "serverPassword": "${{ steps.obs-password.outputs.password }}",
            "authenticationRequired": true
          }' > ~/.config/obs-studio/plugin_config/obs-websocket/obsWebSocket.json

      - name: Start OBS in background
        run: |
          obs --startvirtualcam --minimize-to-tray &
          echo $! > obs.pid 
          sleep 50
